// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMA_nsfrUieNDEeO7ts-Kh5WnlfZiAV14',
    appId: '1:60795356473:web:5d3584e74cbcca110a94e8',
    messagingSenderId: '60795356473',
    projectId: 'restcountryapiapk',
    authDomain: 'restcountryapiapk.firebaseapp.com',
    storageBucket: 'restcountryapiapk.firebasestorage.app',
    measurementId: 'G-1K1EJS21CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmwF2rMJL6FD2MgnGrkDcGnNcFMtConxQ',
    appId: '1:60795356473:android:a2f4330d5cdcb5ce0a94e8',
    messagingSenderId: '60795356473',
    projectId: 'restcountryapiapk',
    storageBucket: 'restcountryapiapk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8v1L29ztHGl4xo9w7EpPb_K7PPEDBN0',
    appId: '1:60795356473:ios:0d65ce61253780080a94e8',
    messagingSenderId: '60795356473',
    projectId: 'restcountryapiapk',
    storageBucket: 'restcountryapiapk.firebasestorage.app',
    iosBundleId: 'com.example.getCountryApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8v1L29ztHGl4xo9w7EpPb_K7PPEDBN0',
    appId: '1:60795356473:ios:0d65ce61253780080a94e8',
    messagingSenderId: '60795356473',
    projectId: 'restcountryapiapk',
    storageBucket: 'restcountryapiapk.firebasestorage.app',
    iosBundleId: 'com.example.getCountryApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMA_nsfrUieNDEeO7ts-Kh5WnlfZiAV14',
    appId: '1:60795356473:web:7fa51ec49321d7f70a94e8',
    messagingSenderId: '60795356473',
    projectId: 'restcountryapiapk',
    authDomain: 'restcountryapiapk.firebaseapp.com',
    storageBucket: 'restcountryapiapk.firebasestorage.app',
    measurementId: 'G-X7VDD5C2MP',
  );
}
